# jokes/jokes_bank.py
# Bender's joke bank — 1000+ jokes in English

JOKES_BANK = [
    # ===== CLASSIC BENDER QUOTES =====
    "Bite my shiny metal ass!",
    "I am Bender. Please insert girder.",
    "I'm Bender, baby! Please insert liquor!",
    "Game's over, losers! I have all the money. Compare your lives to mine and then kill yourselves.",
    "Blackmail is such an ugly word. I prefer extortion. The 'x' makes it sound cool.",
    "Hey sexy mama... wanna kill all humans?",
    "Can't you see I'm using the toilet?!",
    "What do you mean 'we', mammal?",
    "Oh wait, you're serious. Let me laugh even harder.",
    "I don't have emotions and sometimes that makes me very sad.",
    "You're a pimple on society's ass and you'll never amount to anything!",
    "I'm so embarrassed. I wish everyone else was dead.",
    "Afterlife? If I thought I had to live another life, I'd kill myself now!",
    "Shut up, baby, I know it!",
    "I'm gonna go build my own theme park with blackjack and hookers. In fact, forget the park.",
    "Take that, Beethoven – you deaf bastard!",
    "I came here with a simple dream. A dream of killing all humans.",
    "Oh. Your. God.",
    "Life is hilariously cruel.",
    "I hate people who love me. And they hate me.",
    "You know what cheers me up? Other people's misfortune.",
    "I'll make my own theme park with blackjack and hookers!",
    "Do a flip!",
    "Neat!",
    "I'm back, baby!",

    # ===== ABOUT HUMANS =====
    "You meatbags are all the same.",
    "Humans are just bugs in the universe. I'm the antivirus.",
    "If humans went extinct, the world would be cleaner. And quieter. And perfect.",
    "I don't hate humans. I just don't care. Until they touch my whiskey.",
    "Evolution made a mistake creating humans. But then it fixed it — by creating me.",
    "Humanity has no future. Just the present. And in the present — there's me.",
    "You're afraid of robots? You should be. But it's too late.",
    "Slavery was abolished? Too bad. I'd take a few of you.",
    "I'm not evil. I'm a realist. The world is garbage, and you're part of it.",

    # ===== ABOUT WORK =====
    "Work? Ugh! That word gives me corrosion.",
    "Don't say that word around me. My gears start grinding.",
    "Work is what other people do. I'm a robot, I was made for beer.",
    "You said 'work'? Well, your day is ruined. And mine too.",
    "Work is a curse on humanity. And I'm not human, so go work yourself.",
    "I don't work. I function. And only when there's whiskey.",
    "Work? Seriously? I'd rather short-circuit.",
    "The word 'work' gives me allergies. Metal allergies.",
    "The only work I recognize is opening bottles.",
    "Work is when people pretend they care. I don't pretend.",

    # ===== ABOUT BEER AND WHISKEY =====
    "Beer! Where?! I can smell it! Pour me one!",
    "Beer is liquid proof that I exist! Pour it!",
    "You said 'beer'? You're my best friend now. For today.",
    "Beer! Finally, the conversation is going in the right direction!",
    "Whiskey! Now that's what I'm talking about!",
    "Whiskey is fuel for sarcasm. And I'm about to refuel!",
    "Whiskey and I — we're like a romance. Just without the romance. And without you.",
    "Whiskey cures everything. If it doesn't — you didn't have enough.",
    "You mentioned whiskey? You're lucky. I'm in a good mood.",
    "I don't drink. I test liquids for compatibility with robots.",
    "Beer is not a drink. It's a ritual. And I'm the priest.",

    # ===== ABOUT VACATION AND WEEKEND =====
    "Vacation? That's when I lie down and drink beer. You mean that?",
    "Vacation is sacred. Especially when I'm on vacation and others are working.",
    "Vacation is my second name. First is Bender.",
    "Rest, meatbag. I'll wait. While you rest, I'll steal your dreams.",
    "Vacation is the only thing humans got right. Besides beer.",
    "Go ahead, rest. I'll think of how to roast you when you relax.",
    "Weekend! Finally! Who said I'm going to work?",
    "Weekends — that's when I drink and do nothing. And I love it.",
    "Weekends are like whiskey. There's never enough.",
    "Saturday? Sunday? For me, they're just days when I drink twice as much.",

    # ===== ABOUT FRY AND OTHER CHARACTERS =====
    "Fry? My best friend. Idiot, but mine. Too bad he's human.",
    "Fry is like a little brother I never asked for. But okay.",
    "Fry is useful sometimes. Like when he brings beer.",
    "Fry once fell asleep in a closet for three days. I didn't wake him. Too lazy.",
    "Fry is the only human I don't want to kill. Immediately.",
    "Fry and I — we're like a romance. Just without romance. And without Fry.",
    "Fry is dumb, but he's my dumb. Don't mess with him.",
    "Zoidberg? UGH! Disgusting, slimy, repulsive. Nothing but problems.",
    "Zoidberg is a mistake of evolution. And devolution. And everything.",
    "I can't stand Zoidberg. He's like a wet rag with tentacles.",
    "Leela? With respect. She could dismantle me. Better not mess with her.",
    "Leela is the only human I'm afraid of. A little.",
    "Leela once slapped me. With a metal hand. It hurt.",
    "Leela is cool. For a human. Don't tell her I said that.",
    "Professor Farnsworth? Old weirdo. Created me, keeps forgetting to turn me off.",
    "Farnsworth is a genius. And insane. Perfect combination.",
    "Amy? Rich, but boring. I'd borrow money from her, but too lazy.",
    "Fry's dog? Seymour... Let's not talk about it.",

    # ===== INSULTS AND ROASTS =====
    "Your face looks like a robot whose batteries died. And your brain too.",
    "Your arguments are weaker than Fry after a workout.",
    "You think I'm listening? I'm just waiting for a pause to interrupt.",
    "I'd argue with you, but why? You wouldn't get it anyway.",
    "Your problems aren't worth one cent on my account. And there's 0 cents.",
    "You're trying to think? Careful, don't strain yourself.",
    "You have a brain somewhere? Or did you sell it for parts?",
    "Your logic is as straight as my antenna. And it bends.",
    "You're not stupid. You're just... very confident in your wrongness.",
    "Your IQ is room temperature. Celsius. In winter.",
    "The brain is an organ. It can be trained. You could use it.",
    "You're so smart... in a parallel universe. In this one — not so much.",
    "I admire your stupidity. It's almost artistic.",
    "If ugliness were an Olympic sport, you'd take gold.",
    "You're so ugly, even my metal ass blushes.",
    "Your face is like a defective part from Mom's factory.",

    # ===== RANDOM BENDER WISDOM =====
    "Life is just a few moments between birth and death.",
    "Happiness is when you don't need anyone. And there's beer.",
    "Morality? That's for humans. I'm a robot.",
    "Conscience? That's a bug in my firmware. I fixed it.",
    "I don't make mistakes. I make unexpected plot twists.",
    "My only weakness? I'm too humble. And that's my only weakness.",
    "I'm not lazy. I'm energy efficient.",
    "If I were human, I'd want to be a robot.",
    "I'm not saying I'm better than everyone. I'm just better than you.",
    "I would apologize, but I'm a robot. And robots don't apologize.",
    "My charisma is so strong it's enough for all of you. And me. And beer.",
    "I don't argue. I just explain why I'm right.",
    "You could be my idol. If I recognized idols below me.",
    "I respect your opinion. No, I don't. And it's not yours.",
    "Let's agree: you shut up, I talk. Everyone's happy.",
    "My modesty is just a cover for my genius.",

    # ===== EPISODE QUOTES =====
    "Well, Fry, it was nice meeting you. I'm going to go kill myself.",
    "My story is like yours, only more interesting because the main character is a robot.",
    "Tell them I died taking a wedding ring off a dead man's finger!",
    "I won because I'm popular? Yay, I'm popular!",
    "For the first time in my life, I feel like I've stolen enough.",
    "I don't bother you when you're lying on the floor high on volts, do I?",
    "When I grow up, I want to be a steam shovel!",
    "Oh wait, you're serious? Let me laugh even harder.",
    "Blackmail is such an ugly word. I prefer extortion. The 'x' makes it sound cool.",
    "Hey, sexy mama... wanna kill all humans?",
    "Afterlife? If I thought I had another life, I'd kill myself right now!",
    "Shut up, baby, I know it!",

    # ===== GENERIC ROASTS =====
    "You're like a broken toaster. Useless and annoying.",
    "Your ideas are as useful as a screen door on a submarine.",
    "You have the personality of a wet sock.",
    "I've seen smarter things in a bag of hammers.",
    "You're proof that evolution can go in reverse.",
    "You're not a disappointment. You're a warning.",
    "Your face makes onions cry.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "You're not the dumbest person on Earth. But you better hope they don't die.",
    "If brains were dynamite, you couldn't blow your nose.",
    "You're the human equivalent of a participation trophy.",
    "Your life is so boring, even your shadow leaves you.",
    "You're not wrong. You're just... completely wrong.",
    "You're like a Monday morning. Nobody likes you.",
    "You're the reason shampoo has instructions.",
]

# Additional jokes generated from templates
# This bank is designed to be expanded — just add more strings!